"""Static data tables for Myanmar Bedin / Mahabote."""

from __future__ import annotations

from .models import MahaboteHouseDefinition, ZodiacAnimal

# Traditional 8-house ring.
MAHABOTE_HOUSES: tuple[MahaboteHouseDefinition, ...] = (
    MahaboteHouseDefinition("binga", "Binga", "本命宮", "ဘင်္ဂ", "Identity and core temperament", "本質、性格與生命基調", "positive"),
    MahaboteHouseDefinition("athun", "Athun", "財福宮", "အထွန်း", "Resources and prosperity flow", "資源、財福與累積能力", "positive"),
    MahaboteHouseDefinition("yaza", "Yaza", "權勢宮", "ရာဇာ", "Authority, position, influence", "權勢、地位與影響力", "positive"),
    MahaboteHouseDefinition("adipati", "Adipati", "主導宮", "အဓိပတိ", "Leadership, command, executive power", "主導力、決策與執行", "positive"),
    MahaboteHouseDefinition("marana", "Marana", "無常宮", "မရဏ", "Impermanence, endings, transformation", "無常、轉折、終結與重生", "liability"),
    MahaboteHouseDefinition("thike", "Thike", "障礙宮", "သိုက်", "Obstacles, friction, delay", "阻礙、摩擦與延宕", "liability"),
    MahaboteHouseDefinition("puti", "Puti", "耗損宮", "ပုတိ", "Loss, burden, karmic debts", "耗損、壓力與業債", "liability"),
    MahaboteHouseDefinition("kamma", "Kamma", "業力宮", "ကမ္မ", "Karma, duty, consequences", "業力、責任與果報", "liability"),
)

# House order used to place lords (starts from House of Impermanence).
HOUSE_FILL_ORDER: tuple[int, ...] = (4, 5, 6, 7, 0, 1, 2, 3)

# 7-lord cycle used by year-mod-7 start.
LORD_ORDER: tuple[str, ...] = (
    "sun",
    "moon",
    "mars",
    "mercury",
    "jupiter",
    "venus",
    "saturn",
)

# Optional fixed step for placing the next house lord in the 7-lord cycle.
LORD_FILL_STEP: int = 1

ZODIAC_8: tuple[ZodiacAnimal, ...] = (
    ZodiacAnimal(
        key="sun_garuda",
        animal_en="Garuda",
        animal_zh="迦樓羅",
        animal_emoji="🦅",
        planet_en="Sun",
        planet_zh="太陽",
        planet_symbol="☉",
        direction_en="NE",
        direction_zh="東北",
        element_en="Fire",
        element_zh="火",
        color_hex="#D4AF37",
        traits_en=("visionary", "noble", "protective"),
        traits_zh=("有遠見", "氣度高", "保護欲強"),
        auspicious_activities_en=("leadership decisions", "launching projects", "public visibility"),
        auspicious_activities_zh=("領導決策", "新案啟動", "公開曝光"),
        caution_activities_en=("ego conflicts", "rushed investment"),
        caution_activities_zh=("自我衝突", "衝動投資"),
        remedies_en=("offer water and light on Sunday dawn", "practice humility before major negotiations"),
        remedies_zh=("週日黎明供水與點燈", "重大談判前先修謙卑"),
        favorable_directions_en=("NE", "E"),
        favorable_directions_zh=("東北", "東"),
        caution_directions_en=("SW",),
        caution_directions_zh=("西南",),
    ),
    ZodiacAnimal(
        key="moon_tiger",
        animal_en="Tiger",
        animal_zh="虎",
        animal_emoji="🐅",
        planet_en="Moon",
        planet_zh="月亮",
        planet_symbol="☽",
        direction_en="E",
        direction_zh="東",
        element_en="Water",
        element_zh="水",
        color_hex="#B0C4DE",
        traits_en=("sensitive", "adaptive", "empathetic"),
        traits_zh=("敏感", "適應強", "同理心高"),
        auspicious_activities_en=("family healing", "education", "creative writing"),
        auspicious_activities_zh=("家庭修復", "學習進修", "文創寫作"),
        caution_activities_en=("emotional overreaction", "late-night overwork"),
        caution_activities_zh=("情緒過激", "熬夜過勞"),
        remedies_en=("moon meditation on Monday night", "keep hydration routine"),
        remedies_zh=("週一夜晚做月亮冥想", "維持規律補水"),
        favorable_directions_en=("E", "NE"),
        favorable_directions_zh=("東", "東北"),
        caution_directions_en=("W",),
        caution_directions_zh=("西",),
    ),
    ZodiacAnimal(
        key="mars_lion",
        animal_en="Lion",
        animal_zh="獅",
        animal_emoji="🦁",
        planet_en="Mars",
        planet_zh="火星",
        planet_symbol="♂",
        direction_en="SE",
        direction_zh="東南",
        element_en="Fire",
        element_zh="火",
        color_hex="#C0392B",
        traits_en=("bold", "competitive", "decisive"),
        traits_zh=("果斷", "競爭心強", "行動快"),
        auspicious_activities_en=("sports and training", "legal assertion", "technical execution"),
        auspicious_activities_zh=("運動訓練", "權益主張", "技術執行"),
        caution_activities_en=("aggressive arguments", "high-risk conflict"),
        caution_activities_zh=("好鬥爭執", "高風險衝突"),
        remedies_en=("martial discipline and breathwork", "offer red flowers on Tuesday"),
        remedies_zh=("練習呼吸與紀律", "週二供紅花"),
        favorable_directions_en=("SE", "S"),
        favorable_directions_zh=("東南", "南"),
        caution_directions_en=("NW",),
        caution_directions_zh=("西北",),
    ),
    ZodiacAnimal(
        key="mercury_elephant",
        animal_en="Tusked Elephant",
        animal_zh="有牙象",
        animal_emoji="🐘",
        planet_en="Mercury",
        planet_zh="水星",
        planet_symbol="☿",
        direction_en="S",
        direction_zh="南",
        element_en="Earth",
        element_zh="土",
        color_hex="#2E8B57",
        traits_en=("analytical", "communicative", "strategic"),
        traits_zh=("理性", "善溝通", "策略型"),
        auspicious_activities_en=("contracts", "business planning", "language learning"),
        auspicious_activities_zh=("簽約談判", "商務規劃", "語言學習"),
        caution_activities_en=("gossip", "overthinking"),
        caution_activities_zh=("口舌是非", "過度思慮"),
        remedies_en=("charity through stationery/books", "keep written daily intentions"),
        remedies_zh=("捐贈文具書籍", "每日書寫願行"),
        favorable_directions_en=("S", "SE"),
        favorable_directions_zh=("南", "東南"),
        caution_directions_en=("N",),
        caution_directions_zh=("北",),
    ),
    ZodiacAnimal(
        key="rahu_tuskless_elephant",
        animal_en="Tuskless Elephant",
        animal_zh="無牙象",
        animal_emoji="🐘",
        planet_en="Rahu",
        planet_zh="羅睺",
        planet_symbol="☊",
        direction_en="SW",
        direction_zh="西南",
        element_en="Shadow",
        element_zh="影",
        color_hex="#8E44AD",
        traits_en=("mystic", "unconventional", "karmic"),
        traits_zh=("靈性強", "非典型", "業力感重"),
        auspicious_activities_en=("retreat and purification", "research", "healing service"),
        auspicious_activities_zh=("靜修淨化", "深度研究", "療癒服務"),
        caution_activities_en=("speculative gambling", "obsessive control"),
        caution_activities_zh=("投機賭博", "執念控制"),
        remedies_en=("weekly incense offering", "silent fasting or digital detox"),
        remedies_zh=("每週供香", "靜默齋戒或數位斷捨"),
        favorable_directions_en=("SW", "W"),
        favorable_directions_zh=("西南", "西"),
        caution_directions_en=("NE",),
        caution_directions_zh=("東北",),
    ),
    ZodiacAnimal(
        key="jupiter_rat",
        animal_en="Rat",
        animal_zh="鼠",
        animal_emoji="🐀",
        planet_en="Jupiter",
        planet_zh="木星",
        planet_symbol="♃",
        direction_en="W",
        direction_zh="西",
        element_en="Air",
        element_zh="風",
        color_hex="#4169E1",
        traits_en=("wise", "ethical", "generous"),
        traits_zh=("智慧", "重倫理", "樂於助人"),
        auspicious_activities_en=("teaching", "legal affairs", "mentorship"),
        auspicious_activities_zh=("教學傳承", "法律事務", "導師角色"),
        caution_activities_en=("moral rigidity", "over-promising"),
        caution_activities_zh=("道德僵化", "過度承諾"),
        remedies_en=("donate educational support", "gratitude practice on Thursday"),
        remedies_zh=("捐助教育資源", "週四行感恩修持"),
        favorable_directions_en=("W", "NW"),
        favorable_directions_zh=("西", "西北"),
        caution_directions_en=("E",),
        caution_directions_zh=("東",),
    ),
    ZodiacAnimal(
        key="venus_guinea_pig",
        animal_en="Guinea Pig",
        animal_zh="天竺鼠",
        animal_emoji="🐹",
        planet_en="Venus",
        planet_zh="金星",
        planet_symbol="♀",
        direction_en="NW",
        direction_zh="西北",
        element_en="Water",
        element_zh="水",
        color_hex="#DB7093",
        traits_en=("charming", "artistic", "harmonizing"),
        traits_zh=("有魅力", "審美強", "擅長調和"),
        auspicious_activities_en=("arts, beauty, diplomacy", "relationship healing"),
        auspicious_activities_zh=("藝術美學", "外交協調", "關係修復"),
        caution_activities_en=("excess indulgence", "vanity-driven spending"),
        caution_activities_zh=("過度享樂", "虛榮消費"),
        remedies_en=("acts of kindness to partners", "fragrance and cleanliness ritual on Friday"),
        remedies_zh=("對伴侶行善", "週五香氛淨身儀式"),
        favorable_directions_en=("NW", "W"),
        favorable_directions_zh=("西北", "西"),
        caution_directions_en=("SE",),
        caution_directions_zh=("東南",),
    ),
    ZodiacAnimal(
        key="saturn_naga",
        animal_en="Naga",
        animal_zh="那伽",
        animal_emoji="🐉",
        planet_en="Saturn",
        planet_zh="土星",
        planet_symbol="♄",
        direction_en="N",
        direction_zh="北",
        element_en="Earth",
        element_zh="土",
        color_hex="#5D6D7E",
        traits_en=("disciplined", "resilient", "patient"),
        traits_zh=("紀律", "耐力", "穩重"),
        auspicious_activities_en=("long-term planning", "infrastructure work", "monastic discipline"),
        auspicious_activities_zh=("長期規劃", "基建實作", "戒律修行"),
        caution_activities_en=("pessimism", "social isolation"),
        caution_activities_zh=("悲觀退縮", "人際封閉"),
        remedies_en=("serve elders and workers", "grounding routine before sunrise"),
        remedies_zh=("服務長者與勞動者", "日出前接地靜修"),
        favorable_directions_en=("N", "NW"),
        favorable_directions_zh=("北", "西北"),
        caution_directions_en=("S",),
        caution_directions_zh=("南",),
    ),
)

ZODIAC_BY_LORD_KEY = {
    "sun": ZODIAC_8[0],
    "moon": ZODIAC_8[1],
    "mars": ZODIAC_8[2],
    "mercury": ZODIAC_8[3],
    "jupiter": ZODIAC_8[5],
    "venus": ZODIAC_8[6],
    "saturn": ZODIAC_8[7],
}

# Full 8-cycle index mapping for annual overlays.
ZODIAC_BY_CYCLE_INDEX = {idx: zodiac for idx, zodiac in enumerate(ZODIAC_8)}
